# Generated by Django 4.0.6 on 2022-08-26 10:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inito', '0009_alter_emailnewsletter_email_richtext_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
