# Generated by Django 4.0.6 on 2022-08-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inito', '0010_alter_article_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='EmailNewsletter',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
